name: checks

on:
  push:
  pull_request:
    paths:
      - ".github/workflows/checks.yml"
      - "dist/index.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Checksum
        run: npm run checksum
